### ISSUE TITLE
Mozaik will not work on Mac OS x El Capitan

### ISSUE THREAD

**Issue by AHaymond** [plouc/mozaik#105]
Running `npm install` inside the cloned mozaik-demo directory ends up failing and producing the following error log.

``` 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'mozaik-dashboard' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 silly mapToRegistry name mozaik-dashboard
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'mozaik-dashboard',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   name: 'mozaik-dashboard',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/mozaik-dashboard
9 verbose request uri https://registry.npmjs.org/mozaik-dashboard
10 verbose request no auth needed
11 info attempt registry request try #1 at 2:55:51 PM
12 verbose request id baeaf2ff051e1ad2
13 http request GET https://registry.npmjs.org/mozaik-dashboard
14 http 404 https://registry.npmjs.org/mozaik-dashboard
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Tue, 06 Sep 2016 20:55:51 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-ord1745-ORD',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1473195351.616351,VS0,VE345',
15 verbose headers   vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Tue, 06 Sep 2016 20:55:51 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-ord1745-ORD',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1473195351.616351,VS0,VE345',
16 silly get     vary: 'Accept-Encoding' } ]
17 error owner ls Couldn't get owner data mozaik-dashboard
18 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/mozaik-dashboard
18 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
18 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at Request.emit (events.js:172:7)
18 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
18 verbose stack     at emitOne (events.js:82:20)
18 verbose stack     at Request.emit (events.js:169:7)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
19 verbose statusCode 404
20 verbose pkgid mozaik-dashboard
21 verbose cwd /Users/adamhaymond/Projects/mozaik-demo
22 error Darwin 15.6.0
23 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "mozaik-dashboard"
24 error node v4.5.0
25 error npm  v2.15.9
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/mozaik-dashboard
27 error 404
27 error 404 'mozaik-dashboard' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]
```

**Comment by AHaymond** [comment]
updated to latest node/npm and got it working... for now

**Comment by plouc** [comment]
@AHaymond, yes, it's specified in the `package.json` (`engines`), I'll probably add `engine-strict` flag to make it more clear.
