### ISSUE TITLE
install error npm install

### ISSUE THREAD

**Issue by dduleep** [plouc/mozaik#115]
|
> mozaik-dashboard@ postinstall /home/ubuntu/workspace/mozaik-demo-master
> if $BUILD_ASSETS; then npm run build-assets; fi

> mozaik-dashboard@ build-assets /home/ubuntu/workspace/mozaik-demo-master
> gulp build

module.js:327
    throw err;
    ^

Error: Cannot find module 'babelify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/mozaik-demo-master/node_modules/mozaik/gulp/tasks/js.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "run" "build-assets"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

**Comment by plouc** [comment]
You should try with npm 3 => https://github.com/plouc/mozaik/blob/master/package.json#L15

**Comment by plouc** [comment]
Any news on this using npm3 or yarn ? I close this issue as it has been inactive for a while.
