### ISSUE TITLE
On version 2, when using the demo the server.js failed

### ISSUE THREAD

**Issue by lslinnet** [plouc/mozaik#163]
Just checking out the demo repo from github, checking out the mozaik-2 branch and starting the server.js.

Further testing showed that this was due to fails in the npm install process. which are shown as an option on the website.

```
➜  mozaik-demo git:(mozaik-2) ✗ node --version
v10.5.0
➜  mozaik-demo git:(mozaik-2) ✗ npm --version
6.3.0
➜  mozaik-demo git:(mozaik-2) ✗ node server.js
> using config file: 'conf/config.yml'

/Users/larslinnet/Sites/mozaik-demo/server.js:11
Mozaik.configureFromFile(configPath)
       ^

TypeError: Mozaik.configureFromFile is not a function
    at Object.<anonymous> (/Users/larslinnet/Sites/mozaik-demo/server.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

**Comment by lslinnet** [comment]
Seems this might have been outdated node_modules :/

**Comment by juhamust** [comment]
Relates: https://github.com/plouc/mozaik-demo/issues/17

**Comment by djschoone** [comment]
The solution in https://github.com/plouc/mozaik-demo/issues/17 fixes the demo. I think the instruction misses starting your server `node server.js`
