### ISSUE TITLE
Unexpected "indent" in src/core/styl/_mixins.styl

### ISSUE THREAD

**Issue by cluebcke** [plouc/mozaik#17]
When running `gulp publish` for the first time, I encountered the following error:
```shell
[12:49:08] Starting 'react'...
Potentially unhandled rejection [2] ParseError: /Users/cluebcke/projects/tools/mozaik/src/core/styl/_mixins.styl:3:21
   1| transition($value)
   2|   -webkit-transition $value; /* Saf3.2+, Chrome */
   3|      -moz-transition $value; /* FF4+ */
--------------------------^
   4|       -ms-transition $value;
   5|        -o-transition $value; /* Opera 10.5+ */
   6|           transition $value;

unexpected "indent"

    at Parser.error (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:257:11)
    at Parser.stmt (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:798:32)
    at Parser.statement (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:669:21)
    at Parser.block (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:840:21)
    at Parser.functionDefinition (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:1714:21)
    at Parser [as function] (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:1655:18)
    at Parser.stmt (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:762:26)
    at Parser.statement (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:669:21)
    at Parser.parse (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:234:25)
    at Evaluator.importFile (/Users/cluebcke/projects/tools/mozaik/node_modules/gulp-stylus/node_modules/stylus/lib/visitor/evaluator.js:73:20)
```
I've fixed it (pull request coming), but I don't know why this would be happening for me and not others. My platform information is below:

OS: OS X 10.10.1
Python: 2.7.6
Node: v0.11.16

**Comment by plouc** [comment]
@cluebcke it's strange, did you try with a stable node version ?

**Comment by cluebcke** [comment]
As noted on the other issue, I went from io -> node 0.10 -> node 0.11. I'm entirely willing to believe that I only had issues because I wasn't paying close attention in the first place.

By the way, sorry that reporting these couple of probably-my-own-fault issues is my first interaction with you. This is a really, really cool project and will be immediately useful to me.

**Comment by plouc** [comment]
No problem :) actually I don't use nvm or n, I experienced problems with some npm packages using it, I use VMs for more *on the edge* projects with a single version. Some packages use native addons through node-gyp, perhaps not fully compatible with version switching. And I'm glad to hear this project was useful to you.
