### ISSUE TITLE
How to update an existing project ?

### ISSUE THREAD

**Issue by tlenclos** [plouc/mozaik#41]
I runned `npm update` and after your refactoring with ES6 the app crash.

```
╰─$ node app.js                                                                                                   1 ↵
/Users/thibz/Documents/github/dashboard/node_modules/mozaik/src/Mozaik.js:6
class Mozaik {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/thibz/Documents/github/dashboard/app.js:1:81)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Is there a recommended way to update mozaik for an existing project ?

**Comment by plouc** [comment]
@tlenclos you should take your actual config and move it to an updated demo repo clone or use the yeoman generator. I hope it'll solve your problem, let me know if it doesn't.

**Comment by plouc** [comment]
@tlenclos did it worked ?

**Comment by tlenclos** [comment]
Partially, there is some custom widgets that are broken but I just changed theses files from the mozaik-demo repository and it works.

```
app.js
src/App.jsx
package.json
```
