### ISSUE TITLE
gulp not finding reflux module

### ISSUE THREAD

**Issue by torbjornvatn** [plouc/mozaik#45]
Hi,

I tried to set up a new dashboard using the Yeoman approach, but I ran into this error when executing `gulp build`

```node
[11:14:06] Using gulpfile ~/Development/node/unaboard/gulpfile.js
[11:14:06] Starting 'copy:fonts'...
[11:14:06] Copying fonts
[11:14:06] Starting 'copy:styles'...
[11:14:06] Copying styles
[11:14:06] Starting 'copy:imgs'...
[11:14:06] Copying images from extensions and themes
[11:14:06] Starting 'collect:styles'...
[11:14:06] Collecting extensions styles
[11:14:06] Finished 'collect:styles' after 5.75 ms
[11:14:06] Starting 'styles:dev'...
[11:14:06] Compiling stylus code using theme '/Users/torvatn/Development/node/unaboard/node_modules/mozaik/src/themes/bordeau'
[11:14:06] Starting 'js:dev'...
[11:14:06] Finished 'copy:imgs' after 46 ms
[11:14:06] Finished 'copy:styles' after 287 ms
[11:14:06] Finished 'styles:dev' after 277 ms
[11:14:06] Starting 'styles'...
[11:14:06] Finished 'styles' after 5.38 μs
[11:14:06] Finished 'copy:fonts' after 426 ms
[11:14:06] Starting 'copy'...
[11:14:06] Finished 'copy' after 7.66 μs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'reflux' from '/Users/torvatn/Development/node/unaboard/node_modules/mozaik-ext-twitter/lib/components'
    at /Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/torvatn/Development/node/unaboard/node_modules/mozaik/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any ideas on how to fix this? 

I'm using `node v4.1.2` and `npm v2.14.6` by the way

**Comment by torbjornvatn** [comment]
I've tried pulling the demo-repo, and that works just fine

**Comment by torbjornvatn** [comment]
I removed the twitter extension from `app.js` but the I got this from the image extension: 

```node 
info: registered API "github"
info: registered API "heroku"
module.js:338
    throw err;
    ^

Error: Cannot find module 'mozaik-ext-image/client'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/torvatn/Development/node/unaboard/app.js:10:34)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

I altered `app.js` to contain `mozaik-ext-image/components` instead, but then I got this:

```node 
info: registered API "github"
info: registered API "heroku"
/Users/torvatn/Development/node/unaboard/node_modules/mozaik/src/Bus.js:51
            this.apis[id] = api(this._mozaik);
                            ^

TypeError: api is not a function
    at Bus.registerApi (/Users/torvatn/Development/node/unaboard/node_modules/mozaik/src/Bus.js:33:25)
    at Object.<anonymous> (/Users/torvatn/Development/node/unaboard/app.js:10:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by plouc** [comment]
@torbjornvatn is your repo available somewhere ?

**Comment by torbjornvatn** [comment]
Got it working, seems like it was a problem with our inhouse npm registry
