### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by foodaka** [plouc/mozaik#81]
everytime i try and load the npm install i come across this error. any idea what to do?

```
/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
Error: Invalid mapping: {"generated":{"line":33220,"column":10},"source":"Branch.jsx","original":{},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:105:14)
    at /Users/work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/index.js:40:15
    at Array.forEach (native)
    at Generator.addMappings (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/index.js:38:12)
    at Combiner._addExistingMap (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:33:18)
    at Combiner.addFile (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:58:12)
    at Transform.write [as _transform] (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/index.js:62:23)
    at Transform._read (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at Transform.pipeOnReadable (/Users//work/mozaik-demo/node_modules/mozaik/node_modules/browserify/node_modules/browser-pack/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by plouc** [comment]
@foodaka, which Mozaïk version do you use ? What method did you used for installation (mozaik-demo/yeoman generator), and finally which version of node/npm are your running Mozaïk on ?

**Comment by plouc** [comment]
ok you used the mozaik-demo, the path is in the stack trace :)

**Comment by foodaka** [comment]
thanks for the quick reply. node v4.2.3

**Comment by plouc** [comment]
and for npm ?

**Comment by foodaka** [comment]
npm 2.14.7

**Comment by plouc** [comment]
hum, I get the same error… it's weird because the demo is automatically deployed on heroku and it works, I must have missed something, don't have the time to fix it now, but I'll look later

**Comment by foodaka** [comment]
ok thanks drop me a ping, i would love to try out this solution

**Comment by plouc** [comment]
@foodaka, you can pull the demo repo / rm node_modules and re-install, should be ok

**Comment by foodaka** [comment]
awesome thanks got it up and running. users may run into error with babelify, just run

` npm install babelify`

**Comment by plouc** [comment]
I use npm@3, modules get flattened, I think that's why babelify is available for me and not for you.
I close it as it seems to work, thanks for your report.

**Comment by plouc** [comment]
I think you had a warning on installation
```json
"engines": {
    "node": "0.12.x",
    "npm" : ">=3.0.0"
  },
```

**Comment by modomodo** [comment]
@plouc I'm still getting errors with the mozaik-demo

Here's the output:
```sh
/home/mike/Documents/maramoja/mozaik-demo/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
        ^

Error: Invalid mapping: {"generated":{"line":42757,"column":10},"source":"Branch.jsx","original":{},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/mike/Documents/maramoja/mozaik-demo/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/mike/Documents/maramoja/mozaik-demo/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:105:14)
    at /home/mike/Documents/maramoja/mozaik-demo/node_modules/inline-source-map/index.js:40:15
    at Array.forEach (native)
    at Generator.addMappings (/home/mike/Documents/maramoja/mozaik-demo/node_modules/inline-source-map/index.js:38:12)
    at Combiner._addExistingMap (/home/mike/Documents/maramoja/mozaik-demo/node_modules/combine-source-map/index.js:33:18)
    at Combiner.addFile (/home/mike/Documents/maramoja/mozaik-demo/node_modules/combine-source-map/index.js:58:12)
    at Transform.write [as _transform] (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/index.js:62:23)
    at Transform._read (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at Transform.pipeOnReadable (/home/mike/Documents/maramoja/mozaik-demo/node_modules/browser-pack/node_modules/readable-stream/lib/_stream_readable.js:664:5)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-assets"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! mozaik-dashboard@ build-assets: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mozaik-dashboard@ build-assets script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mozaik-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mozaik-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mozaik-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mike/Documents/maramoja/mozaik-demo/npm-debug.log
```

I'm currently using Ubuntu 16.04

**Comment by plouc** [comment]
@modomodo can you show me the content of your package.json please ?

**Comment by modomodo** [comment]
I'm using the default settings. I haven't changed anything from the mozaik-demo:
```js
{
  "name": "mozaik-dashboard",
  "description": "Mozaïk demo dashboard",
  "repository": {
    "type": "git",
    "url": "git://github.com/plouc/mozaik-demo"
  },
  "license": "MIT",
  "author": {
    "name": "Raphaël Benitte",
    "url": "https://github.com/plouc"
  },
  "engines": {
    "node": "0.12.x",
    "npm" : ">=3.0.0"
  },
  "dependencies": {
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babel-register": "6.7.2",
    "dotenv": "^0.5.1",
    "gulp": "^3.9.0",
    "lodash": "^3.10.0",
    "mozaik": "1.3.0",
    "mozaik-ext-github": "1.2.1",
    "mozaik-ext-time": "1.1.0",
    "mozaik-ext-travis": "1.1.0",
    "mozaik-ext-weather": "1.2.0",
    "react": "^0.13.3"
  },
  "scripts": {
    "test": "npm run build-assets",
    "start": "node app.js",
    "postinstall": "if $BUILD_ASSETS; then npm run build-assets; fi",
    "build-assets": "gulp build"
  }
}
```

**Comment by plouc** [comment]
@modomodo you can just re-pull the repo / rm node_modules and re-install, should fix your problem

**Comment by modomodo** [comment]
Its now working. Thanks alot @plouc :+1: 

What exactly was the problem?

**Comment by plouc** [comment]
mozaik-ext-github required an higher version of mozaik

**Comment by plouc** [comment]
of the mozaik dependencies

**Comment by tomav** [comment]
Had the same problem today. Upgrading `mozaik` fixed it.
Thank you.
